class AddColumnsToBoreholeWellConfid < ActiveRecord::Migration
  def change
    add_column :borehole_well_confids, :eno, :decimal
    add_column :borehole_well_confids, :confid, :string
    add_column :borehole_well_confids, :phase, :string
    add_column :borehole_well_confids, :date_created, :datetime
    add_column :borehole_well_confids, :accumulation, :string
    add_column :borehole_well_confids, :acreage_summary, :string
    add_column :borehole_well_confids, :actual_well_purpose, :string
    add_column :borehole_well_confids, :admin_reg, :string
    add_column :borehole_well_confids, :admin_reg_abbrev, :string
    add_column :borehole_well_confids, :associated_well_eno, :decimal
    add_column :borehole_well_confids, :contractor, :string
    add_column :borehole_well_confids, :cont_abbrev, :string
    add_column :borehole_well_confids, :country, :string
    add_column :borehole_well_confids, :der_ko_depth, :decimal
    add_column :borehole_well_confids, :der_prop_total_depth, :decimal
    add_column :borehole_well_confids, :der_tot_depth_sub_sea, :decimal
    add_column :borehole_well_confids, :discovery, :string
    add_column :borehole_well_confids, :disc_type, :string
    add_column :borehole_well_confids, :drillers_total_depth, :decimal
    add_column :borehole_well_confids, :drillers_total_depth_units, :string
    add_column :borehole_well_confids, :easting, :decimal
    add_column :borehole_well_confids, :elev, :decimal
    add_column :borehole_well_confids, :est_cost, :decimal
    add_column :borehole_well_confids, :facility, :string
    add_column :borehole_well_confids, :file_number, :string
    add_column :borehole_well_confids, :ga_basin, :string
    add_column :borehole_well_confids, :ga_location, :string
    add_column :borehole_well_confids, :ga_sub_basin, :string
    add_column :borehole_well_confids, :ga_summary, :string
    add_column :borehole_well_confids, :hc_show, :string
    add_column :borehole_well_confids, :hole_class, :string
    add_column :borehole_well_confids, :hole_name, :string
    add_column :borehole_well_confids, :incl_type, :string
    add_column :borehole_well_confids, :kb_rt, :string
    add_column :borehole_well_confids, :kb_rt_height, :decimal
    add_column :borehole_well_confids, :ko_depth, :decimal
    add_column :borehole_well_confids, :ko_depth_units, :string
    add_column :borehole_well_confids, :leg, :string
    add_column :borehole_well_confids, :loggers_depth_units, :string
    add_column :borehole_well_confids, :loggers_total_depth, :decimal
    add_column :borehole_well_confids, :max_dev, :decimal
    add_column :borehole_well_confids, :near_accumulation, :string
    add_column :borehole_well_confids, :northing, :decimal
    add_column :borehole_well_confids, :on_off, :string
    add_column :borehole_well_confids, :operator, :string
    add_column :borehole_well_confids, :operator_abbrev, :string
    add_column :borehole_well_confids, :op_abn, :string
    add_column :borehole_well_confids, :op_acn, :string
    add_column :borehole_well_confids, :op_arbn, :string
    add_column :borehole_well_confids, :orig_elev, :decimal
    add_column :borehole_well_confids, :orig_elev_units_measure, :string
    add_column :borehole_well_confids, :orig_geo_datum, :string
    add_column :borehole_well_confids, :orig_kb_rt_height, :decimal
    add_column :borehole_well_confids, :orig_kb_rt_height_units, :string
    add_column :borehole_well_confids, :orig_lat_dec_degrees, :decimal
    add_column :borehole_well_confids, :orig_lat_degrees, :decimal
    add_column :borehole_well_confids, :orig_lat_minutes, :decimal
    add_column :borehole_well_confids, :orig_lat_seconds, :decimal
    add_column :borehole_well_confids, :orig_long_dec_degrees, :decimal
    add_column :borehole_well_confids, :orig_long_degrees, :decimal
    add_column :borehole_well_confids, :orig_long_minutes, :decimal
    add_column :borehole_well_confids, :orig_long_seconds, :decimal
    add_column :borehole_well_confids, :orig_td_easting, :decimal
    add_column :borehole_well_confids, :orig_td_lat_dec_degrees, :decimal
    add_column :borehole_well_confids, :orig_td_lat_deg, :decimal
    add_column :borehole_well_confids, :orig_td_lat_min, :decimal
    add_column :borehole_well_confids, :orig_td_lat_sec, :decimal
    add_column :borehole_well_confids, :orig_td_long_dec_degrees, :decimal
    add_column :borehole_well_confids, :orig_td_long_deg, :decimal
    add_column :borehole_well_confids, :orig_td_long_min, :decimal
    add_column :borehole_well_confids, :orig_td_long_sec, :decimal
    add_column :borehole_well_confids, :orig_td_northing, :decimal
    add_column :borehole_well_confids, :orig_td_zone, :decimal
    add_column :borehole_well_confids, :parent_well_eno, :decimal
    add_column :borehole_well_confids, :parent_well_name, :string
    add_column :borehole_well_confids, :post_drill, :string
    add_column :borehole_well_confids, :pref_total_depth, :decimal
    add_column :borehole_well_confids, :pref_total_depth_units, :string
    add_column :borehole_well_confids, :pre_drill, :string
    add_column :borehole_well_confids, :prop_target_depth, :decimal
    add_column :borehole_well_confids, :prop_target_depth_units, :string
    add_column :borehole_well_confids, :reason_for_cessation, :string
    add_column :borehole_well_confids, :rig_capacity, :string
    add_column :borehole_well_confids, :rig_make, :string
    add_column :borehole_well_confids, :rig_model, :string
    add_column :borehole_well_confids, :rig_name, :string
    add_column :borehole_well_confids, :rig_no, :string
    add_column :borehole_well_confids, :rig_release_date, :datetime
    add_column :borehole_well_confids, :rig_type, :string
    add_column :borehole_well_confids, :sidetrack_purpose, :string
    add_column :borehole_well_confids, :spud_date, :datetime
    add_column :borehole_well_confids, :sub_cost, :decimal
    add_column :borehole_well_confids, :subsidy, :string
    add_column :borehole_well_confids, :td_depth_date, :datetime
    add_column :borehole_well_confids, :td_lat_dec_degrees, :decimal
    add_column :borehole_well_confids, :td_long_dec_degrees, :decimal
    add_column :borehole_well_confids, :tests_entered, :string
    add_column :borehole_well_confids, :title, :string
    add_column :borehole_well_confids, :total_depth, :decimal
    add_column :borehole_well_confids, :tot_cost, :decimal
    add_column :borehole_well_confids, :tvd_subsea, :decimal
    add_column :borehole_well_confids, :tvd_subsea_units, :string
    add_column :borehole_well_confids, :utm_zone, :decimal
    add_column :borehole_well_confids, :v_dat_type, :string
    add_column :borehole_well_confids, :wcr_basin, :string
    add_column :borehole_well_confids, :wcr_location, :string
    add_column :borehole_well_confids, :wcr_sub_basin, :string
    add_column :borehole_well_confids, :wcr_summary, :string
    add_column :borehole_well_confids, :weekly_comments, :string
    add_column :borehole_well_confids, :well_abbreviation, :string
    add_column :borehole_well_confids, :well_alias, :string
    add_column :borehole_well_confids, :well_comm, :string
    add_column :borehole_well_confids, :well_lat_dec_degrees, :decimal
    add_column :borehole_well_confids, :well_long_dec_degrees, :decimal
    add_column :borehole_well_confids, :well_objective, :string
    add_column :borehole_well_confids, :well_purpose, :string
    add_column :borehole_well_confids, :well_status, :string
    add_column :borehole_well_confids, :well_summary, :string
    add_column :borehole_well_confids, :well_uno, :string
    add_column :borehole_well_confids, :zone, :string
    add_column :borehole_well_confids, :proposed_rig_name, :string
    add_column :borehole_well_confids, :proposed_spud_date, :datetime
    add_column :borehole_well_confids, :proposed_td_date, :datetime
  end
end
